version: 2.1

 workflows:
   test-deploy:
      jobs:
          - test
          
          
     jobs:
       test:
       
       docker:
          - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run: java --version
