version: 2.1

   test-deploy: 
      jobs:
          - test
          
          
     jobs:
       test:
       
       docker:
          - image: cimg/openjdk:17.0.3-node
    steps:
      - checkout
      - run: java --version
      
